# Generated by Django 6.1.1 on 2026-09-23 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('category', models.CharField(choices=[('cultural_heritage', 'Культурное наследие'), ('street_art', 'Уличное искусство'), ('abandoned', 'Заброшенные пространства'), ('nature', 'Природные уголки')], max_length=32, verbose_name='Категория')),
                ('solitude_level', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=16, verbose_name='Уровень уединённости')),
                ('activity_type', models.CharField(choices=[('walk', 'Прогулка'), ('photo', 'Фотосессия'), ('bike', 'Велосипед'), ('run', 'Бег')], max_length=16, verbose_name='Тип активности')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500, verbose_name='Ссылка на файл')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео')], max_length=8, verbose_name='Тип медиа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='mapapp.location', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('activity_type', models.CharField(choices=[('walk', 'Прогулка'), ('photo', 'Фотосессия'), ('bike', 'Велосипед'), ('run', 'Бег')], max_length=16, verbose_name='Тип активности')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Длительность, минут')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mapapp.location', verbose_name='Объект')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mapapp.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='RouteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок в маршруте')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_locations', to='mapapp.location', verbose_name='Объект')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_locations', to='mapapp.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подтверждения')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='mapapp.location', verbose_name='Объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение',
                'verbose_name_plural': 'Подтверждения',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['author'], name='idx_location_user'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['location'], name='idx_media_location'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['author'], name='idx_route_user'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='idx_comment_user'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['location'], name='idx_comment_location'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['route'], name='idx_comment_route'),
        ),
        migrations.AddIndex(
            model_name='routelocation',
            index=models.Index(fields=['route'], name='idx_route_location_route'),
        ),
        migrations.AddIndex(
            model_name='routelocation',
            index=models.Index(fields=['location'], name='idx_route_location_location'),
        ),
        migrations.AlterUniqueTogether(
            name='routelocation',
            unique_together={('route', 'order')},
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['user'], name='idx_verification_user'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['location'], name='idx_verification_location'),
        ),
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together={('user', 'location')},
        ),
    ]
