# Generated by Django 5.0.14 on 2026-09-25 15:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(default=1.0)),
                ('reverse_cost', models.FloatField(default=1.0)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'mapapp_roadedge',
            },
        ),
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('object', 'Объект'), ('route', 'Маршрут')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('verifications', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('track', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('category', models.CharField(blank=True, choices=[('Культурное наследие', 'Культурное наследие'), ('Уличное искусство', 'Уличное искусство'), ('Природный объект', 'Природный объект'), ('Парки и отдых', 'Парки и отдых'), ('Маршруты', 'Маршруты')], max_length=50)),
                ('privacy', models.CharField(blank=True, choices=[('тихий', 'Тихий'), ('средний', 'Средний'), ('высокий', 'Высокий')], max_length=20)),
                ('activity_type', models.CharField(blank=True, choices=[('Прогулка', 'Прогулка'), ('Фотосессия', 'Фотосессия'), ('Велосипед', 'Велосипед'), ('Экскурсия', 'Экскурсия'), ('Пеший маршрут', 'Пеший маршрут'), ('Веломаршрут', 'Веломаршрут'), ('Бег', 'Бег')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='map_items/')),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект / Маршрут',
                'verbose_name_plural': 'Объекты и маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('map_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mapapp.mapitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='mapapp.mapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('map_item', 'user')},
            },
        ),
    ]
